CREATE SCHEMA IF NOT EXISTS class3;

CREATE TABLE IF NOT EXISTS class3.pessoas (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    datanascimento DATE NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    datahoracriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
